### ISSUE TITLE
@zimme <-> @bruz

### ISSUE THREAD

**Issue by zimme** [MeteorCommunity/chat#12]
Hey @bruz

Would you mind adding the issue tracker to https://github.com/bruz/meteor-github-api?

Also, in the code... I'm not seeing that `target` is ever being used.

**Comment by bruz** [comment]
Thanks for spotting that, I hadn't even realized issues wasn't turned on for the repo.

`target` does indeed seem to be unused. I've removed the dead code related to that.

**Comment by zimme** [comment]
No problem :+1:
